sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    Note right of browser: JSON: {"content":"{{note}}","date":"{{timestamp}}"}
    activate server
    server-->>browser: {"message":"note created"} (Status: 201)
    deactivate server
